### ISSUE TITLE
Provider resources should not be deleted until all resources referring to it are deleted

### ISSUE THREAD

**Issue by muvaf** [crossplaneio/crossplane-runtime#116]
### What problem are you facing?

When I delete an infra-stack, all CRDs get deletion requests, including `Provider` ones. Since there is no `finalizer` on `Provider` resources, they are deleted immediately. This leads to hanging resources with deletion timestamp because their controllers cannot make deletion calls anymore since they'd have to have `Provider` resource to give them the credentials.

### How could Crossplane help solve your problem?

Crossplane could block the deletion of a `Provider` resources until all resources that used this `Provider` are deleted from the cluster.

One mechanism could be that every resource that is successfully created could add its identification info to `finalizers` array and remove its entry when its deleted.

The other alternative would be to have a `Provider` controller that scans all the resources who refer to this `Provider` instance and block the deletion until it finds none. We could somehow make use of labels for easy listing instead of `providerRef`.

**Comment by negz** [comment]
The finalizer approach seems like the simplest, but I suspect it might be a little opaque to users. We'd need to somehow represent why the provider was not yet being deleted.

I almost wonder whether we should maintain a back-reference from the provider to the managed resources that use it, so it's obvious to users how and where the provider is in use. e.g.:

```yaml
status:
  inUseBy:
    resourceRefs:
    - apiVersion: database.gcp.crossplaneio/v1beta1
      kind: CloudSQLInstance
      name: cool
    - apiVersion: database.gcp.crossplaneio/v1beta1
      kind: CloudSQLInstance
      name: lame
```

Under such an approach I imagine each managed resource controller would need to update the provider (which might be racy?), and we'd need a provider controller to add/remove a finalizer based on whether the provider was in use.
