### ISSUE TITLE
Static provisioning requires nonsensical managed resources

### ISSUE THREAD

**Issue by negz** [crossplaneio/crossplane-runtime#28]
### What happened?

Changes were made to our resource claim controller watch predicates recently in https://github.com/crossplaneio/crossplane-runtime/pull/18 and https://github.com/crossplaneio/crossplane-runtime/pull/24. The latter refactored the watch predicates used by resource claim controllers with the intention of supporting both statically and dynamically provisioned managed resources. It does this by accepting resources that satisfy any of three watch predicates, applied in the following order:

1. `resource.HasManagedResourceReferenceKind` accepts resource claims with a `.spec.resourceRef` to the kind of managed resource the reconciler is concerned with.
1. `resource.HasDirectClassReferenceKind` accepts managed resources with a `.spec.classRef` to the kind of non-portable class the reconciler is concerned with.
1. `resource.HasIndirectClassReferenceKind` accepts resource claims with a `.spec.classRef` to a portable class with a `.classRef` to the kind of non-portable class the reconciler is concerned with.

In retrospect `resource.HasDirectClassReferenceKind` only makes sense in a dynamic provisioning context, because statically provisioned managed resources don't use a resource class, and thus typically don't set their `.spec.classRef`. Based on my read of the current predicate logic (I have not confirmed this) I expect our resource claim reconcilers would never notice changes to statically provisioned managed resources.

This is not too big an issue given the resource claim reconciler only watches managed resources to wait for them to become bindable, which they typically do before the resource claim is created in a static provisioning scenario. I'm guessing that's why I didn't encounter this case when I tested static provisioning per https://github.com/crossplaneio/crossplane-runtime/pull/24#issuecomment-531460570.

### How can we reproduce it?

1. Create a resource claim that references a managed resource that does not yet exist.
1. Create the referenced managed resource.

My guess is that the claim will never bind.

There are two workarounds for this:
1. Create the managed resource and wait for it its `.status.bindingPhase` to become `Unbound` before creating a resource claim that references it.
1. Set the managed resource's `.spec.classRef.kind` and `.spec.classRef.apiVersion` to its corresponding non-portable resource class kind.

### What environment did it happen in?
crossplane-runtime version: 26a458d

**Comment by negz** [comment]
We can fix this pretty easily by deprecating `resource.HasDirectClassReferenceKind` and replacing it with a new `resource.IsManagedKind` predicate that accepts all resources of the supplied kind:

```go
func IsManagedKind(k ManagedKind, ot runtime.ObjectTyper) PredicateFn {
	return func(obj runtime.Object) bool {
		// We probably want a GetKind variant of MustGetKind that returns
		// an error instead of panicing.
		gvk, err := runtime.MustGetKind(obj, ot)
		if err != nil {
			return false
		}
		return gvk == schema.GroupVersionKind(k)
	}
}
```

**Comment by negz** [comment]
I'd like to reopen this issue in the spirit of integrating early. I've raised https://github.com/crossplaneio/crossplane/pull/860 to update the developer guide to match the change. @hasheddan did you happen to test whether this fix works as expected per the reproduction steps in this issue?

P.S. I noticed during the doc update that `IsManagedKind` takes its arguments as `kind, scheme` while the existing `HasIndirectClassReferenceKind` takes its arguments as `scheme, kinds`. I don't think it's worth fixing, but I do wish I could unsee the lack of symmetry. 😭

**Comment by hasheddan** [comment]
@negz it appears that the claim stays in the `Managed claim is waiting for managed resource to become bindable` state and never binds to the managed resource

Managed Resource:
```yaml
  Binding Phase:  Unbound
  Conditions:
    Last Transition Time:  2019-10-01T19:41:05Z
    Reason:                Managed resource is available for use
    Status:                True
    Type:                  Ready
    Last Transition Time:  2019-10-01T19:38:05Z
    Reason:                Successfully reconciled managed resource
    Status:                True
    Type:                  Synced
```

Claim:
```yaml
Conditions:
    Last Transition Time:  2019-10-01T19:38:02Z
    Reason:                Managed claim is waiting for managed resource to become bindable
    Status:                False
    Type:                  Ready
    Last Transition Time:  2019-10-01T19:38:02Z
    Reason:                Successfully reconciled managed resource
    Status:                True
    Type:                  Synced
```

**Comment by negz** [comment]
@hasheddan Thanks for testing that out!

There are three scenarios we need to make sure the claim reconciler handles:

1. Dynamic provisioning. No managed resource exists. A resource claim is created with a portable class reference and without a managed resource reference. In this case the claim reconciler should dynamically provision and then bind to a managed resource.
1. Resource-first static provisioning. A managed resource is created explicitly, without using a resource class. Later (or simultaneously), a resource claim that references (via its resource reference) that managed resource is created. We should skip dynamic provisioning and go straight to binding.
1. Claim-first static provisioning. A resource claim is created that references (via its resource reference) a managed resource that does not yet exist. We should fail to reconcile that resource claim until such time as the referenced managed resource is created (out of band) and becomes bindable, at which point we should bind to it.

I'd like to be sure scenarios 1 and 2 still work as expected, because I think they're more common and important than case 3. As a lower priority, we should figure out why case 3 isn't working and fix that.

**Comment by negz** [comment]
FWIW - based only on following the reconciler code and not actually testing it - I'd expect scenario three to result in a nil pointer exception in the claim reconciler:

1. We get the claim.
1. We try to get the referenced managed resource and find that it does not exist. We ignore this error and proceed.
1. We determine that the managed resource was not created, so we try to create it. This involves getting the name of claim's portable class reference, which is nil, so I'd expect a panic here.

My _theory_ is that instead of using `IgnoreNotFound` at claim reconciler line 305, we should handle `NotFound` by requeueing after a short wait. This way we'd only attempt to dynamically provision a managed resource if the resource claim did not already explicitly reference one.

**Comment by negz** [comment]
Another possible issue with static provisioning is that as far as I can tell we never actually set the managed resource's claim reference during the static provisioning codepath (we only set it when we dynamically provision new managed resources). The `EnqueueRequestForClaim` watch handler will only enqueue reconciles for managed resources that have a claim reference set, i.e. only dynamically provisioned managed resources. :( This might explain the behaviour you're seeing.

**Comment by negz** [comment]
It sounds like there's a chance static provisioning is currently broken in master - I'm assigning this to myself to investigate and fix before we ship 0.4.

**Comment by negz** [comment]
Confirming that static provisioning seems broken. When I submit the following:

```yaml
---
apiVersion: database.gcp.crossplane.io/v1beta1
kind: CloudsqlInstance
metadata:
  name: example
spec:
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: cloudsqlinstance-example
  forProvider:
    databaseVersion: POSTGRES_9_6
    region: us-west2
    settings:
      tier: db-custom-1-3840
      dataDiskType: PD_SSD
      dataDiskSizeGb: 10
  providerRef:
    name: example
  reclaimPolicy: Delete
---
apiVersion: database.crossplane.io/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: app-postgresql
spec:
  resourceRef:
    apiVersion: database.gcp.crossplane.io/v1beta1
    kind: CloudsqlInstance
    name: example
  writeConnectionSecretToRef:
    name: postgresqlconn
  engineVersion: "9.6"
```

I eventually see the managed resource become available for binding (i.e. binding phase `Unbound`):
```
Status:
  # ...
  Binding Phase:                    Unbound
  Conditions:
    Last Transition Time:  2019-10-24T08:15:03Z
    Reason:                Successfully resolved managed resource references to other resources
    Status:                True
    Type:                  ReferencesResolved
    Last Transition Time:  2019-10-24T08:15:09Z
    Reason:                Successfully reconciled managed resource
    Status:                True
    Type:                  Synced
    Last Transition Time:  2019-10-24T08:19:10Z
    Reason:                Managed resource is available for use
    Status:                True
    Type:                  Ready
Events:                    <none>
```

Meanwhile the PostgreSQLInstance says:

```
Status:
  Conditions:
    Last Transition Time:  2019-10-24T08:15:53Z
    Reason:                Managed claim is waiting for managed resource to become bindable
    Status:                False
    Type:                  Ready
    Last Transition Time:  2019-10-24T08:15:53Z
    Reason:                Successfully reconciled managed resource
    Status:                True
    Type:                  Synced
```
